version: "3"
services: 
    nginx:
        build: 
            context: ./Nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
        restart: always
        volumes:
            - .:/var/www
    client:
        build:
            context: ./Client
            dockerfile: Dockerfile
        ports: 
            - 5000:80